bundleid: net.turbare.copy-serial
connections:
  copy_serial: []
  get_serial:
  - destinationuid: copy_serial
createdby: Akihiro Uchida
description: copy serial number to clipboard
disabled: false
name: alfred-copy-serial
objects:
- config:
    argumenttype: 2
    keyword: serial
    script: !include './get_serial'
    title: copy serial number
    withspace: false
  type: alfred.workflow.input.scriptfilter
  uid: get_serial
- config:
    script: !include './copy_serial'
  type: alfred.workflow.action.script
  uid: copy_serial
readme: '!include README'
uidata:
  copy_serial:
    ypos: 60.0
  get_serial:
    ypos: 60.0
webaddress: turbare.net
